services:
  zookeeper:
    image: zookeeper:3.9
    container_name: psed2-zookeeper
    ports:
      - "2181:2181"

  pact-broker-db:
    image: postgres:16-alpine
    container_name: psed2-pact-broker-db
    environment:
      POSTGRES_DB: pact_broker
      POSTGRES_USER: pact_broker
      POSTGRES_PASSWORD: pact_broker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pact_broker -d pact_broker"]
      interval: 5s
      timeout: 5s
      retries: 20

  pact-broker:
    image: pactfoundation/pact-broker:latest
    container_name: psed2-pact-broker
    depends_on:
      pact-broker-db:
        condition: service_healthy
    environment:
      PACT_BROKER_DATABASE_URL: "postgres://pact_broker:pact_broker@pact-broker-db:5432/pact_broker"
      PACT_BROKER_LOG_LEVEL: INFO
    ports:
      - "9292:9292"
