spring.application.name=rate-printer
spring.main.web-application-type=none
spring.cloud.zookeeper.connect-string=localhost:2181
spring.cloud.zookeeper.discovery.register=false
spring.cloud.zookeeper.discovery.root=/services
provider.url=http://currency-rate-provider/rpc
poll.interval.ms=5000
poll.initial-delay.ms=1000
