spring.application.name=rate-printer
server.port=8081
spring.cloud.zookeeper.connect-string=localhost:2181
spring.cloud.zookeeper.discovery.register=false
spring.cloud.zookeeper.discovery.root=/services
provider.url=http://currency-rate-provider/api/v1/rpc
poll.interval.ms=5000
poll.initial-delay.ms=1000
poll.pair=USD/RUB
client.name=${spring.application.name}
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.client.requests=true
management.metrics.distribution.percentiles.http.client.requests=0.5,0.95,0.99
