spring.application.name=currency-rate-provider
server.port=8080
spring.cloud.zookeeper.connect-string=localhost:2181
spring.cloud.zookeeper.discovery.register=true
spring.cloud.zookeeper.discovery.root=/services
spring.cloud.zookeeper.discovery.instance-host=localhost
